defaults: &defaults
  # Org name of the website.
  org_name: "hopodemtot"

  # City or organization.
  place_name: "Barcelona"

  # Names for the moderation console, as a hint for moderators
  # to know better how to assign users with official positions
  official_level_1_name: "Col·laboradors"
  official_level_2_name: "Voluntari HPT"
  official_level_3_name: "Empleat públic"
  official_level_4_name: "Grup promotor"
  official_level_5_name: "Cap de llista"

    #level_0: No és un càrrec públic
    #level_1: Empleat/da públic
    #level_2: Organització general
    #level_3: Director/a General
    #level_4: Regidor/a
    #level_5: Alcaldessa

  # Max percentage of allowed anonymous votes on a debate
  max_ratio_anon_votes_on_debates: 50

  # Max votes where a debate is still editable
  max_votes_for_debate_edit: 1000

  # Max votes where a proposal is still editable
  max_votes_for_proposal_edit: 10

  # Prefix for the Proposal codes
  proposal_code_prefix: 'HPT'

  # Number of votes needed for proposal success
  votes_for_proposal_success: 100

  # Users with this email domain will automatically be marked as level 1 officials
  # Emails under the domain's subdomains will also be included
  email_domain_for_officials: ''

  twitter_handle: "hopodemtot_cat"
  facebook_handle: "hopodemtot"
  youtube_handle: "channel/UClGrbn9T9wHManduOwy432w"
  #instagram_handle: ""
  github_handle: "consul/consul"
  facebook_app_id: "248929335445036"

  blog_url: 
    ca: "http://hopodemtot.info/"
    es: "http://hopodemtot.info/"
    en: "http://hopodemtot.info/"

  url: "https://hopodemtot.info"

  # Users with this email domain will automatically be marked as level 1 officials
  # Emails under the domain's subdomains will also be included
  email_domain_for_officials: ''

  # Code to be included at the top (header) of every page (useful for tracking)
  per_page_code: ''

  feature.debates: false
  feature.debates.vote: false
  feature.debates.search: false
  feature.spending_proposals: false
  feature.proposal_tags: false
  feature.proposal_video_url: false
  feature.meeting_tags: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
